export const STORAGE_KEYS = {
  GET_USER: 'getUserDetails',
  GET_PARENT_USER_DETAILS: 'getParentUserDetails',
  GET_FAMILY_PLAYERS: 'getFamilyPlayers',
  GET_FAQS: 'getFaqs',
  TOKEN: 'TOKEN',
  GET_PLAYER:'getPlayer',
  GET_ALL_PLAYERS_DATA:'getAllPlayerData',
  GET_ANNOUNCEMENTS: "getAnnouncements",
  PARENTID:'getParentId',
  GET_TIER:'getTier',
  GET_REDEEM:'getRedeem',
  GET_ACTIVITY:'getActivity',
  GET_PERFORMANCE:'getPerformance',
  GET_PERFORMANCE_DATA:'getPerformanceData',
  GET_PLAYER_ID:'getPlayerId',
  GET_PAYMENT:'getPayment',
  GET_ROLES:"getRoles",
  ROLES_LIST:"rolesList",
  GET_COACH_INFO:'getCoachInfo',
  GET_PARENT_DATA:'getParentData',
  COACH_BATCH:'getCoachBatch',
  COACH_ACTIVITY:'getCoachActivity',
  GET_PROFILE:'getPlayerProfile',
  GET_ALL_PERFORMANCE:'getAllPerformance',
  GET_MANAGER:'getManager',
  GET_AGE_GROUP:'getAgeGroup',
  GET_LOCATION: 'getLocation',
  GET_TOURNAMENT:'getTournament',
  GET_DIVISION:'getDivision',
  GET_OPPONENT:'getOpponent',
  GET_TEAMS:'getTeam',
  GET_DATE:'getDate',
  GET_ALLOCATION:'getAllocation',
  GET_COACH_ATTENDACNE_LIST: 'getCoachAttendacneList',
  GET_FIELDING_SESSION:'getFieldingSession',
  GET_SPONSORS:'getAllSponsors',
  GET_COACH_ID:'getCoachId',
  GET_ABOUT_US:'getAbout',
  GET_ID_BY_EMAIL:'getParentIdByEmail',
  HALL_OF_FAME:'getHallOfFame',
  SUMMARY:'getSummary',
  GET_ALL_PLAYERS:'getAllPlayers',
  GET_ACADEMY_KID_AGE:'getAcademyKidAge',
  GET_ACADEMY_LOCATION:'getAcademyLocation',
  GET_TIMES_PER_WEEK:'getTimesPerWeek',
  GET_LOCATION_KEY:'getLocation',
  GET_TYPE_OF_LANE:'getTypeOfLane',
  GET_HOURS:'getHours',
  GET_RENTAL:`getRental`
};
